version: 2
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    ldflags:
      - '-s -w -X main.Version={{.Version}} -X main.Commit={{.Commit}} -X main.Date={{.Date}} -X main.BuiltBy=goreleaser'

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  -
    id: shellhook
    package_name: shellhook
    homepage: https://github.com/jadolg/shellhook
    maintainer: Jorge Alberto Díaz Orozco (Akiel) <diazorozcoj@gmail.com>
    description: |-
      Execute shell scripts remotely with an HTTP call
    license: MIT
    formats:
      - deb
    bindir: /usr/bin
    section: default
    priority: extra
    scripts:
      postinstall: ./packaging/postinstall.sh
      preremove: ./packaging/preremove.sh
    contents:
      - src: ./config.yaml
        dst: /etc/shellhook/config.yaml
        type: config|noreplace
        file_info:
          mode: 0600
      - src: ./packaging/shellhook.service
        dst: /etc/systemd/system/shellhook.service
        file_info:
          mode: 0600

dockers:
  - id: shellhook-debian-amd64
    dockerfile: debian.Dockerfile
    image_templates:
      - "ghcr.io/jadolg/shellhook:debian-latest-amd64"
      - "ghcr.io/jadolg/shellhook:debian-{{ .Tag }}-amd64"
      - "ghcr.io/jadolg/shellhook:debian-v{{ .Major }}.{{ .Minor }}-amd64"
    use: buildx
    build_flag_templates: &build_flag_templates_amd64
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.description Shellhook is a tool to execute shell scripts remotely with an HTTP call"

  - id: shellhook-debian-arm64
    dockerfile: debian.Dockerfile
    goarch: arm64
    image_templates:
      - "ghcr.io/jadolg/shellhook:debian-latest-arm64"
      - "ghcr.io/jadolg/shellhook:debian-{{ .Tag }}-arm64"
      - "ghcr.io/jadolg/shellhook:debian-v{{ .Major }}.{{ .Minor }}-arm64"
    use: buildx
    build_flag_templates: &build_flag_templates_arm64
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.description Shellhook is a tool to execute shell scripts remotely with an HTTP call"

  - id: shellhook-ubuntu-amd64
    dockerfile: ubuntu.Dockerfile
    use: buildx
    image_templates:
      - "ghcr.io/jadolg/shellhook:ubuntu-latest-amd64"
      - "ghcr.io/jadolg/shellhook:ubuntu-{{ .Tag }}-amd64"
      - "ghcr.io/jadolg/shellhook:ubuntu-v{{ .Major }}.{{ .Minor }}-amd64"
    build_flag_templates:  *build_flag_templates_amd64

  - id: shellhook-ubuntu-arm64
    dockerfile: ubuntu.Dockerfile
    goarch: arm64
    use: buildx
    image_templates:
      - "ghcr.io/jadolg/shellhook:ubuntu-latest-arm64"
      - "ghcr.io/jadolg/shellhook:ubuntu-{{ .Tag }}-arm64"
      - "ghcr.io/jadolg/shellhook:ubuntu-v{{ .Major }}.{{ .Minor }}-arm64"
    build_flag_templates: *build_flag_templates_arm64

  - id: shellhook-alpine-amd64
    dockerfile: alpine.Dockerfile
    image_templates:
      - "ghcr.io/jadolg/shellhook:alpine-latest-amd64"
      - "ghcr.io/jadolg/shellhook:alpine-{{ .Tag }}-amd64"
      - "ghcr.io/jadolg/shellhook:alpine-v{{ .Major }}.{{ .Minor }}-amd64"
    use: buildx
    build_flag_templates: *build_flag_templates_amd64

  - id: shellhook-alpine-arm64
    dockerfile: alpine.Dockerfile
    goarch: arm64
    image_templates:
      - "ghcr.io/jadolg/shellhook:alpine-latest-arm64"
      - "ghcr.io/jadolg/shellhook:alpine-{{ .Tag }}-arm64"
      - "ghcr.io/jadolg/shellhook:alpine-v{{ .Major }}.{{ .Minor }}-arm64"
    use: buildx
    build_flag_templates: *build_flag_templates_arm64

docker_manifests:
  - name_template: "ghcr.io/jadolg/shellhook:debian-latest"
    image_templates:
      - "ghcr.io/jadolg/shellhook:debian-latest-amd64"
      - "ghcr.io/jadolg/shellhook:debian-latest-arm64"

  - name_template: "ghcr.io/jadolg/shellhook:debian-{{ .Tag }}"
    image_templates:
      - "ghcr.io/jadolg/shellhook:debian-{{ .Tag }}-amd64"
      - "ghcr.io/jadolg/shellhook:debian-{{ .Tag }}-arm64"

  - name_template: "ghcr.io/jadolg/shellhook:debian-v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/jadolg/shellhook:debian-v{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/jadolg/shellhook:debian-v{{ .Major }}.{{ .Minor }}-arm64"

  - name_template: "ghcr.io/jadolg/shellhook:ubuntu-latest"
    image_templates:
      - "ghcr.io/jadolg/shellhook:ubuntu-latest-amd64"
      - "ghcr.io/jadolg/shellhook:ubuntu-latest-arm64"

  - name_template: "ghcr.io/jadolg/shellhook:ubuntu-{{ .Tag }}"
    image_templates:
      - "ghcr.io/jadolg/shellhook:ubuntu-{{ .Tag }}-amd64"
      - "ghcr.io/jadolg/shellhook:ubuntu-{{ .Tag }}-arm64"

  - name_template: "ghcr.io/jadolg/shellhook:ubuntu-v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/jadolg/shellhook:ubuntu-v{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/jadolg/shellhook:ubuntu-v{{ .Major }}.{{ .Minor }}-arm64"

  - name_template: "ghcr.io/jadolg/shellhook:alpine-latest"
    image_templates:
      - "ghcr.io/jadolg/shellhook:alpine-latest-amd64"
      - "ghcr.io/jadolg/shellhook:alpine-latest-arm64"

  - name_template: "ghcr.io/jadolg/shellhook:alpine-{{ .Tag }}"
    image_templates:
      - "ghcr.io/jadolg/shellhook:alpine-{{ .Tag }}-amd64"
      - "ghcr.io/jadolg/shellhook:alpine-{{ .Tag }}-arm64"

  - name_template: "ghcr.io/jadolg/shellhook:alpine-v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/jadolg/shellhook:alpine-v{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/jadolg/shellhook:alpine-v{{ .Major }}.{{ .Minor }}-arm64"